server:
  port: 333
  servlet:
    context-path: /banking-app
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cde
    username: root
    password: manju369